version: "3.5"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: techie
    #restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - local

  redis:
    image: redis:5.0
    container_name: redis
    #restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - local

networks:
  local:
    driver: bridge
    name: local
