#!/bin/bash

#base="$( cd "$(dirname "$0")" ; cd ../ ; pwd -P )" # Not with with symlinks
base=~/Code/mreschke/docker
source $base/bin/docker-compose-helper.sh

path=$base/fusionauth/1.14.0
compose "$@"
