#!/bin/bash

# Run container
docker run --name nginx -p 80:80 -p 443:443 -v /private/etc/nginx/conf.d:/etc/nginx/conf.d -v /private/etc/hosts:/etc/hosts -v /private/var/www:/var/www -d mreschke/nginx
