version: "3.5"

services:
  wiki:
    image: requarks/wiki:2
    container_name: wikijs
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: techie
      DB_NAME: wikijs
    ports:
      - "3000:3000"
    networks:
      - local

networks:
  local:
    driver: bridge
    name: local
